#!/bin/bash
set -e
# Create the data directory if it doesn't exist
chmod 775 /data
mkdir -p /data/elasticsearch/logs
chmod -R 775 /data/elasticsearch
chown -R elasticsearch:elasticsearch /data/elasticsearch
echo "Starting elasticsearch..."
cd /opt/elasticsearch
exec /sbin/setuser elasticsearch /opt/elasticsearch/bin/elasticsearch \
    -f -Des.path.data=/data/elasticsearch -Des.path.logs=/data/elasticsearch/logs -Des.cluster.name=graylog2 >> /var/log/elasticsearch.log

